#!/usr/bin/env python
"""Generate a TradingView Pine Script v5 indicator from MATP_table.csv.

The output (MATP_indicator.pine) draws horizontal MATP (orange) and MBP
(green) lines on the chart for any ticker in the screened list. A small
top-right corner badge shows the generation date and how stale the data
is, color-coded:
    white  : <= 14 days
    yellow : 15-30 days
    red    : > 30 days

Usage:
    py scripts/generate_pine.py
"""
from __future__ import annotations

import csv
import sys
from datetime import date
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SKILL_DIR = SCRIPT_DIR.parent
CSV_PATH = SKILL_DIR / "MATP_table.csv"
PINE_PATH = SKILL_DIR / "MATP_indicator.pine"
SKILL_MD_PATH = SKILL_DIR / "SKILL.md"


def read_skill_version() -> str:
    """Pull the version from SKILL.md's YAML frontmatter so the .pine
    stays in lock-step with the skill version. Falls back to 'dev' if
    SKILL.md is missing or the version line can't be found."""
    if not SKILL_MD_PATH.exists():
        return "dev"
    for raw in SKILL_MD_PATH.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if line.startswith("version:"):
            return line.split(":", 1)[1].strip()
        if line == "---" and any(c.isalpha() for c in line):
            # End of frontmatter without finding version.
            break
    return "dev"

TEMPLATE = """\
//@version=5
// MATP/MBP Levels v{version} - auto-generated by generate_pine.py
// Generated: {gen_date}
// Source: https://github.com/kuishung/trading-skills
//
// VERSION
//   This script is version v{version}, generated on {gen_date}.
//   The version comes from the parent skill's SKILL.md and bumps when
//   the skill ships behavior or data-format changes. You can see it
//   live on the chart in the indicator's legend name and in the
//   corner badge.
//
// WHAT IT DOES
//   Draws two horizontal lines on the chart at the Median Analyst Target
//   Price (MATP, orange) and the Max Buy Price (MBP = MATP / 1.15, green)
//   for tickers in the pre-screened list. A corner badge shows when the
//   data was generated and how many days old it is.
//
// HOW TO INSTALL (one-time)
//   1. Open TradingView. Click "Pine Editor" at the bottom of the page.
//   2. Click "Open" -> "New Indicator". Select all the placeholder code
//      and delete it.
//   3. Paste this entire script.
//   4. Click "Save" (any name, e.g. "MATP/MBP Levels").
//   5. Click "Add to chart". The lines appear on any chart whose ticker
//      is in the screened list. Tickers not in the list show only the
//      "no data" badge in the corner.
//
// HOW TO UPDATE (whenever new levels are published)
//   1. Open the latest .pine file from the shared Drive folder.
//   2. Copy its entire contents.
//   3. In TradingView's Pine Editor, open your saved script, select all,
//      delete, paste the new content, then click "Save". All charts that
//      use this indicator refresh automatically.

indicator("MATP/MBP Levels v{version} ({gen_date})", overlay = true)

VERSION        = "{version}"

GENERATED_DATE = "{gen_date}"
GENERATED_TS   = timestamp({gen_year}, {gen_month}, {gen_day}, 0, 0)

matp = switch syminfo.ticker
{matp_cases}
    => na

mbp = switch syminfo.ticker
{mbp_cases}
    => na

has_data = not na(matp)

// Draw horizontal lines via line.new() with xloc.bar_time. Earlier
// attempts:
//   v1.4.3 used line.new() with the default xloc.bar_index — the line
//   sometimes appeared to float against the price coord on zoom.
//   v1.4.5 reverted to plot(), but plot() can render at the wrong
//   Y-position on log-scaled charts when the constant value is far
//   from the historical bars' price range (observed on APH: MBP
//   $156.52 rendered down near $57). plot() also stretches the
//   auto-fit, compressing candles.
// xloc.bar_time anchors the segment in absolute UNIX time, which
// doesn't shift with the visible window the way bar_index can.
// extend.both extends infinitely in both directions, so the line
// always spans the full chart at exactly the price coord.

var line matp_line = na
var line mbp_line  = na
var label matp_lbl = na
var label mbp_lbl  = na

if barstate.islast
    if not na(matp_line)
        line.delete(matp_line)
    if not na(mbp_line)
        line.delete(mbp_line)
    if not na(matp_lbl)
        label.delete(matp_lbl)
    if not na(mbp_lbl)
        label.delete(mbp_lbl)
    if has_data
        matp_line := line.new(time[1], matp, time, matp, xloc=xloc.bar_time, extend=extend.both, color=color.orange, width=2)
        mbp_line  := line.new(time[1], mbp,  time, mbp,  xloc=xloc.bar_time, extend=extend.both, color=color.green,  width=2)
        matp_lbl  := label.new(time, matp, "MATP $" + str.tostring(matp, "#.##"), xloc=xloc.bar_time, color=color.orange, textcolor=color.white, style=label.style_label_left, size=size.small)
        mbp_lbl   := label.new(time, mbp,  "MBP $"  + str.tostring(mbp,  "#.##"), xloc=xloc.bar_time, color=color.green,  textcolor=color.white, style=label.style_label_left, size=size.small)

// Staleness badge in the bottom-right corner. Three rows for clarity:
//   row 0: indicator + version
//   row 1: when the underlying MATP data was generated
//   row 2: age in days, color-coded (white <=14d, yellow 15-30d, red > 30d)
// Bottom-right because TradingView's top corners are usually occupied
// by the chart legend (top-left) and the price-scale UI / currency
// selector / ATR readouts (top-right).
var table info = table.new(position.bottom_right, 1, 3, bgcolor = color.new(color.black, 70), frame_color = color.new(color.white, 50), frame_width = 1)
if barstate.islast
    days_old    = math.round((timenow - GENERATED_TS) / (1000 * 60 * 60 * 24))
    badge_color = days_old <= 14 ? color.white : days_old <= 30 ? color.yellow : color.red
    age_text    = has_data ? str.tostring(days_old) + "d old" : "no data for " + syminfo.ticker
    table.cell(info, 0, 0, "MATP v" + VERSION,            text_color = color.white,  text_size = size.small)
    table.cell(info, 0, 1, "Generated " + GENERATED_DATE, text_color = color.white,  text_size = size.small)
    table.cell(info, 0, 2, age_text,                      text_color = badge_color,  text_size = size.small)
"""


def fmt_case(ticker: str, value: str) -> str:
    return f'    "{ticker}" => {value}'


def main() -> int:
    if not CSV_PATH.exists():
        sys.exit(f"ERROR: CSV not found: {CSV_PATH}. Run the MATP pipeline first.")

    with CSV_PATH.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    if not rows:
        sys.exit(f"ERROR: CSV has no rows: {CSV_PATH}")

    required = {"Ticker", "MATP", "MBP"}
    missing_cols = required - set(rows[0].keys())
    if missing_cols:
        sys.exit(f"ERROR: CSV missing required columns: {missing_cols}")

    matp_cases = "\n".join(fmt_case(r["Ticker"], r["MATP"]) for r in rows)
    mbp_cases  = "\n".join(fmt_case(r["Ticker"], r["MBP"])  for r in rows)

    today = date.today()
    version = read_skill_version()
    pine = TEMPLATE.format(
        version=version,
        gen_date=today.isoformat(),
        gen_year=today.year,
        gen_month=today.month,
        gen_day=today.day,
        matp_cases=matp_cases,
        mbp_cases=mbp_cases,
    )
    PINE_PATH.write_text(pine, encoding="utf-8")
    print(f"Wrote {len(rows)} tickers to {PINE_PATH}")
    print(f"Version:         v{version}")
    print(f"Generated date:  {today.isoformat()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
