#!/usr/bin/env python
"""Generate a TradingView Pine Script v5 indicator from MATP_table.csv.

The output (MATP_indicator.pine) draws horizontal MATP (orange) and MBP
(green) lines on the chart for any ticker in the screened list. A small
top-right corner badge shows the generation date and how stale the data
is, color-coded:
    white  : <= 14 days
    yellow : 15-30 days
    red    : > 30 days

Usage:
    py scripts/generate_pine.py
"""
from __future__ import annotations

import csv
import sys
from datetime import date
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SKILL_DIR = SCRIPT_DIR.parent
CSV_PATH = SKILL_DIR / "MATP_table.csv"
PINE_PATH = SKILL_DIR / "MATP_indicator.pine"

TEMPLATE = """\
//@version=5
// MATP/MBP Levels - auto-generated by generate_pine.py
// Generated: {gen_date}
// Source: https://github.com/kuishung/trading-skills
//
// WHAT IT DOES
//   Draws two horizontal lines on the chart at the Median Analyst Target
//   Price (MATP, orange) and the Max Buy Price (MBP = MATP / 1.15, green)
//   for tickers in the pre-screened list. A corner badge shows when the
//   data was generated and how many days old it is.
//
// HOW TO INSTALL (one-time)
//   1. Open TradingView. Click "Pine Editor" at the bottom of the page.
//   2. Click "Open" -> "New Indicator". Select all the placeholder code
//      and delete it.
//   3. Paste this entire script.
//   4. Click "Save" (any name, e.g. "MATP/MBP Levels").
//   5. Click "Add to chart". The lines appear on any chart whose ticker
//      is in the screened list. Tickers not in the list show only the
//      "no data" badge in the corner.
//
// HOW TO UPDATE (whenever new levels are published)
//   1. Open the latest .pine file from the shared Drive folder.
//   2. Copy its entire contents.
//   3. In TradingView's Pine Editor, open your saved script, select all,
//      delete, paste the new content, then click "Save". All charts that
//      use this indicator refresh automatically.

indicator("MATP/MBP Levels", overlay = true)

GENERATED_DATE = "{gen_date}"
GENERATED_TS   = timestamp({gen_year}, {gen_month}, {gen_day}, 0, 0)

matp = switch syminfo.ticker
{matp_cases}
    => na

mbp = switch syminfo.ticker
{mbp_cases}
    => na

has_data = not na(matp)

// Draw horizontal lines via line.new() with extend.both rather than
// plot(). plot() would stretch TradingView's price-scale auto-fit to
// include MATP/MBP, compressing the actual price action. line.new()
// anchors the line to a price coordinate without affecting auto-scale,
// so the chart stays focused on real candles. The trade-off: if
// MATP/MBP are well outside the current visible price range, the lines
// will be off-screen until the user zooms out or scrolls the scale.

var line  matp_line = na
var line  mbp_line  = na
var label matp_lbl  = na
var label mbp_lbl   = na

if barstate.islast
    if not na(matp_line)
        line.delete(matp_line)
    if not na(mbp_line)
        line.delete(mbp_line)
    if not na(matp_lbl)
        label.delete(matp_lbl)
    if not na(mbp_lbl)
        label.delete(mbp_lbl)
    if has_data
        matp_line := line.new(bar_index - 1, matp, bar_index, matp, extend=extend.both, color=color.orange, width=2)
        mbp_line  := line.new(bar_index - 1, mbp, bar_index, mbp, extend=extend.both, color=color.green, width=2)
        matp_lbl  := label.new(bar_index, matp, "MATP $" + str.tostring(matp, "#.##"), color=color.orange, textcolor=color.white, style=label.style_label_left, size=size.small)
        mbp_lbl   := label.new(bar_index, mbp, "MBP $" + str.tostring(mbp, "#.##"), color=color.green, textcolor=color.white, style=label.style_label_left, size=size.small)

// Price-scale labels on the right Y-axis. display.price_scale shows
// the value as a tag on the axis only, so it doesn't draw anything in
// the chart pane and doesn't affect auto-scaling.
plot(has_data ? matp : na, "MATP", color=color.orange, display=display.price_scale)
plot(has_data ? mbp  : na, "MBP",  color=color.green,  display=display.price_scale)

// Staleness badge in the top-right corner.
var table info = table.new(position.top_right, 1, 1, bgcolor = color.new(color.black, 70))
if barstate.islast
    days_old    = math.round((timenow - GENERATED_TS) / (1000 * 60 * 60 * 24))
    badge_color = days_old <= 14 ? color.white : days_old <= 30 ? color.yellow : color.red
    badge_text  = has_data ? "MATP " + GENERATED_DATE + "  " + str.tostring(days_old) + "d old" : "MATP " + GENERATED_DATE + "  no data for " + syminfo.ticker
    table.cell(info, 0, 0, badge_text, text_color = badge_color, text_size = size.small)
"""


def fmt_case(ticker: str, value: str) -> str:
    return f'    "{ticker}" => {value}'


def main() -> int:
    if not CSV_PATH.exists():
        sys.exit(f"ERROR: CSV not found: {CSV_PATH}. Run the MATP pipeline first.")

    with CSV_PATH.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    if not rows:
        sys.exit(f"ERROR: CSV has no rows: {CSV_PATH}")

    required = {"Ticker", "MATP", "MBP"}
    missing_cols = required - set(rows[0].keys())
    if missing_cols:
        sys.exit(f"ERROR: CSV missing required columns: {missing_cols}")

    matp_cases = "\n".join(fmt_case(r["Ticker"], r["MATP"]) for r in rows)
    mbp_cases  = "\n".join(fmt_case(r["Ticker"], r["MBP"])  for r in rows)

    today = date.today()
    pine = TEMPLATE.format(
        gen_date=today.isoformat(),
        gen_year=today.year,
        gen_month=today.month,
        gen_day=today.day,
        matp_cases=matp_cases,
        mbp_cases=mbp_cases,
    )
    PINE_PATH.write_text(pine, encoding="utf-8")
    print(f"Wrote {len(rows)} tickers to {PINE_PATH}")
    print(f"Generated date: {today.isoformat()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
