"""Render the shared Obsidian vault: company hub notes + per-quarter notes.

The vault is a SHARED, server-side knowledge base (COMPANY_INTELLIGENCE_DESIGN.md):
one set of notes read by every member through the web app, and openable directly
in Obsidian by anyone with the folder. It is not a per-user sync.

Layout (chosen by the user 2026-09-05):

    <vault>/Companies/NVDA.md            hub: guidance-vs-actual history, links
    <vault>/Companies/NVDA/2026-Q3.md    one note per quarter

Why both: a single rolling file cannot be linked, tagged or queried per quarter,
which is the whole point of putting this in Obsidian. The hub is what turns a pile
of notes into a knowledge base -- it is where "who chronically over-promises"
becomes visible, because guided and actual sit in the same row.

Notes are GENERATED and rewritten in place, so anything a human types into them is
lost on the next run. Hand-written analysis belongs in a separate note that
``[[wikilinks]]`` to these -- the header of every generated file says so.
"""
from __future__ import annotations

import datetime as _dt
import os
import re

from ..config import settings

# MarketResearch/ObsidianVault, deliberately:
#   * HermesSync\Vault is the CREDENTIALS folder (alpaca.env, credentials.txt)
#     -- cfg["vault_dir"] in CLAUDE.md. Writing notes there would scatter them
#     through a secrets directory.
#   * The Nous agent can only write inside MarketResearch: its cifs mount
#     /mnt/hermes_sync IS //192.168.1.162/MarketResearch.
#   * HermesSync itself is the Obsidian vault root (.obsidian/ lives there), so
#     notes under MarketResearch/ObsidianVault appear in the existing vault with
#     no extra configuration.
_DEFAULT_VAULT = r"C:\HermesSync\MarketResearch\ObsidianVault"
_SAFE = re.compile(r"[^A-Z0-9.\-]")


def vault_root() -> str:
    return (getattr(settings, "obsidian_dir", None) or "").strip() or _DEFAULT_VAULT


def vault_available() -> bool:
    return os.path.isdir(vault_root())


def _sym(symbol: str) -> str:
    """Uppercase, stripped of anything that could escape the vault directory."""
    return _SAFE.sub("", (symbol or "").strip().upper())


def company_note_path(symbol: str) -> str:
    return os.path.join(vault_root(), "Companies", f"{_sym(symbol)}.md")


def quarter_note_path(symbol: str, period: str) -> str:
    per = _SAFE.sub("", (period or "").strip().upper()) or "UNKNOWN"
    return os.path.join(vault_root(), "Companies", _sym(symbol), f"{per}.md")


_HEADER = ("<!-- GENERATED by TradeHunter. Rewritten on each run - put your own "
           "analysis in a separate note that links here. -->")


def _num(v: float) -> str:
    """Keep the precision the issuer stated.

    ``%g`` renders 108.0 as "108" and 74.0 as "74", quietly dropping the decimal a
    company actually published ("Revenue is expected to be $108.0 billion"). In a
    guidance note that reads as a different, less precise figure, so hold one
    decimal place and only trim beyond that.
    """
    s = f"{v:,.2f}"
    if s.endswith("0") and s[-2] != ".":      # 108.00 -> 108.0, 9.20 -> 9.2
        s = s[:-1]
    return s


def _fmt(v, unit: str | None) -> str:
    if v is None:
        return ""
    if unit == "percent":
        return f"{_num(v)}%"
    if unit == "USD_B":
        return f"${_num(v)}B"
    if unit == "USD_M":
        return f"${_num(v)}M"
    if unit == "USD_per_share":
        return f"${_num(v)}"
    return _num(v)


def _range(row: dict) -> str:
    """A guidance figure as issued: a midpoint, a range, or a midpoint+/-band."""
    unit = row.get("unit")
    lo, mid, hi = row.get("low"), row.get("mid"), row.get("high")
    if mid is not None and lo is not None and hi is not None:
        return f"{_fmt(mid, unit)} ({_fmt(lo, unit)}-{_fmt(hi, unit)})"
    if mid is not None:
        return _fmt(mid, unit)
    if lo is not None and hi is not None:
        return f"{_fmt(lo, unit)}-{_fmt(hi, unit)}"
    return _fmt(lo if lo is not None else hi, unit)


def render_quarter_note(symbol: str, period: str, rows: list[dict],
                        *, filed: str | None = None,
                        source_url: str | None = None) -> str:
    """One quarter's guidance, with the verbatim wording each figure came from."""
    sym = _sym(symbol)
    now = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%d")
    out = [
        "---",
        f"ticker: {sym}",
        f"period: {period}",
        f"filed: {filed or ''}",
        f"source: {source_url or ''}",
        "type: guidance",
        f"updated: {now}",
        f"tags: [guidance, {sym}]",
        "---",
        "",
        _HEADER,
        "",
        f"# {sym} — guidance issued for {period}",
        "",
    ]
    if rows:
        out += ["| Metric | Guidance | Basis |", "|---|---|---|"]
        for r in rows:
            metric = str(r.get("metric", "")).replace("_", " ")
            out.append(f"| {metric} | {_range(r)} | {r.get('basis') or ''} |")
        out += ["", "## Source wording", ""]
        # Quote each distinct sentence once: several metrics often share one.
        seen = set()
        for r in rows:
            s = (r.get("sentence") or "").strip()
            if s and s not in seen:
                seen.add(s)
                out.append(f"> {s}")
                out.append("")
    else:
        out += ["_No quantified guidance in this filing._", "",
                "Many issuers guide only on the earnings call, which is not an SEC "
                "filing. Recorded as a fact so it is distinguishable from "
                "not-yet-fetched.", ""]

    if source_url:
        out += [f"[Source filing]({source_url})", ""]
    out += [f"Company note: [[{sym}]]", ""]
    return "\n".join(out)


def render_company_note(symbol: str, quarters: list[dict],
                        *, name: str | None = None) -> str:
    """The hub: guidance history per quarter, newest first.

    ``quarters`` = [{period, filed, rows: [...], actual: {metric: value}|None}].
    The ``actual`` column is what makes the note worth keeping -- guided beside
    delivered, quarter after quarter.
    """
    sym = _sym(symbol)
    now = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%d")
    out = [
        "---",
        f"ticker: {sym}",
        f"company: {name or ''}",
        "type: company",
        f"updated: {now}",
        f"tags: [company, {sym}]",
        "---",
        "",
        _HEADER,
        "",
        f"# {sym}{' — ' + name if name else ''}",
        "",
        "## Guidance history",
        "",
    ]
    if not quarters:
        out += ["_No guidance captured yet._", ""]
    else:
        out += ["| Period | Metric | Guided | Actual | Filed |", "|---|---|---|---|---|"]
        for q in quarters:
            per = q.get("period", "")
            actual = q.get("actual") or {}
            for r in q.get("rows", []):
                metric = str(r.get("metric", ""))
                act = actual.get(metric)
                out.append(
                    f"| [[{sym}/{per}\\|{per}]] | {metric.replace('_', ' ')} | "
                    f"{_range(r)} | {_fmt(act, r.get('unit')) if act is not None else ''} | "
                    f"{q.get('filed') or ''} |")
        out.append("")
    out += ["## Quarters", ""]
    for q in quarters:
        out.append(f"- [[{sym}/{q.get('period')}]]")
    out.append("")
    return "\n".join(out)


def write_note(path: str, body: str) -> str:
    """Write a note, creating parent folders. Returns the path written."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(body)
    return path
