"""baseline schema

Revision ID: d555dc88d20b
Revises: 
Create Date: 2026-05-31 12:22:35.940174
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd555dc88d20b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matp_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('matp', sa.Float(), nullable=False),
    sa.Column('mbp', sa.Float(), nullable=True),
    sa.Column('last_earnings_date', sa.String(length=20), nullable=True),
    sa.Column('n_targets', sa.Integer(), nullable=True),
    sa.Column('target_high', sa.Float(), nullable=True),
    sa.Column('target_low', sa.Float(), nullable=True),
    sa.Column('target_mean', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('as_of', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matp_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matp_history_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_matp_history_symbol'), ['symbol'], unique=False)

    op.create_table('matp_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('last_earnings_date', sa.String(length=20), nullable=True),
    sa.Column('matp', sa.Float(), nullable=True),
    sa.Column('mbp', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('as_of', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matp_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matp_levels_symbol'), ['symbol'], unique=False)

    op.create_table('matp_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('brokerage', sa.String(length=120), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=False),
    sa.Column('target_date', sa.String(length=20), nullable=True),
    sa.Column('as_of', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'brokerage', 'target_date', 'target_price', name='uq_matp_target')
    )
    with op.batch_alter_table('matp_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matp_targets_symbol'), ['symbol'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('google_sub', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('picture', sa.String(length=512), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finviz_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('pattern', sa.String(length=80), nullable=True),
    sa.Column('trend_state', sa.String(length=20), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('entry', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('profit_target', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('setups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setups_symbol'), ['symbol'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setup_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['setup_id'], ['setups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    with op.batch_alter_table('setups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setups_symbol'))

    op.drop_table('setups')
    op.drop_table('finviz_filters')
    op.drop_table('feedback')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('matp_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matp_targets_symbol'))

    op.drop_table('matp_targets')
    with op.batch_alter_table('matp_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matp_levels_symbol'))

    op.drop_table('matp_levels')
    with op.batch_alter_table('matp_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matp_history_symbol'))
        batch_op.drop_index(batch_op.f('ix_matp_history_as_of'))

    op.drop_table('matp_history')
    # ### end Alembic commands ###
